### ISSUE TITLE
Configure failed to detect missing dep

### ISSUE THREAD

**Issue by Teufelchen1** [pfedick/DeckerGame#181]
**Describe the bug**
I did not have `libdav1d-dev` installed but `./configure` ran fine. Later, the build failed due to missing dep.

**To Reproduce**
1. Freshly clone the repo
2. `cd` into repo, update / submodules
3. Run `./configure` without `libdav1d-dev` installed
4. Observe positive feedback from `./configure`
5. `make -j 16`
6. Observe build failure

```
In file included from src/video/videoplayer.cpp:1:
include/videoplayer.h:13:10: fatal error: dav1d/dav1d.h: No such file or directory
   13 | #include <dav1d/dav1d.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
```

**Expected behavior**
Running `./configure` complains about missing deps.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04

**Additional context**
On my first run of `./configure` it correctly reported I did not have `libmpg123-dev` installed. After installing that, `./configure` was happy. I than run `make` and found this bug.
```
configure: error: Cannot build because of missing dependencies:
  - libmpg123 not found
```

**Comment by pfedick** [comment]
Thanks for reporting this issue.

I have not added a check in configure for libdav1d, yet. I will put it on my todo list.

Thanks,
Patrick

**Comment by pfedick** [comment]
I have added a check to configure
