### ISSUE TITLE
Unable to build on Ubuntu LTS

### ISSUE THREAD

**Issue by Teufelchen1** [pfedick/DeckerGame#182]
**Describe the bug**
The build failed with this error:
```
/usr/bin/ld: pplib/release/libppl7-core.a(asm_blt.o): relocation R_X86_64_32S against `.text' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: failed to set dynamic section sizes: bad value
collect2: error: ld returned 1 exit status
```

**To Reproduce**
1. Ensure all deps are installed and the repo & submodules are up to date
2. Successfully run `./configure`
3. Run `make -j 16`
4. Observe the error

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04

**Comment by pfedick** [comment]
Hello,
I will look into this. It's an issue with some files which are written in assembly and get compiled with nasm. They are written in a way where they can't be loaded as position independent code in memory.

I don't make much use of these functions and there is a fallback to c code, when there is no nasm installed. It won't affect performance of the game. Try:

```
./configure --without-nasm
make
```

Patrick

**Comment by pfedick** [comment]
I think, I have fixed it. It now compiles on windows with mingw64, where I had the same issue. I need to test it on linux...

**Comment by Teufelchen1** [comment]
Trying this:
```
./configure --without-nasm
make
```
worked and I could launch & play!

Regarding your fix, a simple `git pull` did not seem to be enough, I got the same error. When manually switching to `cd pplib/ && git checkout master && git pull` and then building: Successfully builds and plays! (so maybe I am bad with submodules :ghost:)

On a side note: I only use vertical monitors. The intro and menu looked a bit odd but functional & understandable. The game itself also could handle this orientation. I found the game to be really dark and I had trouble seeing what I am doing, maybe that is intentional? The game runs mostly smooth but had some annoying stutters every few seconds especially in the opening / starting cinematic.

Thanks! You may close this issue! :)
